name: build release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        builder: [macos-latest, ubuntu-latest] # windows-latest OpenSSL error
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: make
        
      - name: Package as archive
        shell: bash
        run: |
          echo running archive
          if [[ "${{ matrix.builder }}" == "windows-latest" ]]; then
            7z a ./${{ matrix.builder }}-${{ github.event.repository.name }}.7z ${{ github.event.repository.name }}.exe
          else
            tar czvf ./${{ matrix.builder }}-${{ github.event.repository.name }}.tar.gz ${{ github.event.repository.name }}
          fi

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "./${{ matrix.builder }}-${{ github.event.repository.name }}*"
          body_path: Changes.md
      
